### ISSUE TITLE
Root to portraits is not set locally

### ISSUE THREAD

**Issue by Delpher57** [Levrault/LE-dialogue-editor#33] opened 2021-01-21 06:08 UTC
When creating characters and inserting their respective portraits, the json is exported with the global path and not the local path of the folder

**Enviroment:**
- Windows 10 2004

**Generated JSON:**

```json
{"root":{"next":"34829806-bdc2-4450-9d77-e021f1cffa2b"},"34829806-bdc2-4450-9d77-e021f1cffa2b":{"name":"Godot","portrait":"/Luis Oswaldo/MasterGamer57/testcdddd/1.png","text":{"en":"sasa","fr":""},"next":"cfa4b170-b4bf-42c3-8ca5-337487d1616e"},"cfa4b170-b4bf-42c3-8ca5-337487d1616e":{"name":"sada","portrait":"/Luis Oswaldo/MasterGamer57/testcdddd/rrr/rrr/2.png","text":{"en":"tata","fr":""}},"__editor":{"root":{"uuid":"root","offset":[40,100]},"dialogues":[{"uuid":"34829806-bdc2-4450-9d77-e021f1cffa2b","offset":[240,80],"parent":"root"},{"uuid":"cfa4b170-b4bf-42c3-8ca5-337487d1616e","offset":[780,200]}],"conditions":[],"signals":[],"choices":[]}}
```

**Generated .sfg file:***

```sfg
[path]

file=""
resource="C:/Luis Oswaldo/MasterGamer57/testcdddd"

[locale]

current="en"
selected=[ "en", "fr" ]
custom=[  ]

[variables]

characters=[ {
"name": "Godot",
"portraits": [ {
"name": "1.png",
"path": "/Luis Oswaldo/MasterGamer57/testcdddd/1.png",
"uuid": "a79de44e-c57b-4758-8e56-f33835ded7aa"
} ]
}, {
"name": "sada",
"portraits": [ {
"name": "2.png",
"path": "/Luis Oswaldo/MasterGamer57/testcdddd/rrr/rrr/2.png",
"uuid": "d18abc4a-e48f-41f0-bdae-d83919ec3ee6"
} ]
} ]
files=[ {
"name": "sasa.json",
"path": "/Luis Oswaldo/MasterGamer57/testcdddd/sasa.json"
} ]

[cache]

last_opened_file={
"name": "unregistred_0.json",
"path": "user://test???.unregistred_0.json"
}
```

**Comment by Levrault** [comment] 2021-01-21 18:42
Hi @Delpher57 , 

First of all, thanks for creating the issue. I already created a note and some ways to fix this. At the same time, I will try to make the dialogue file multi-os compatible. I can't tell when it's gonna be fix since I got a lots of work at my day job but I will do my best. And also, don't be shy to create new issue if needed!

![image](https://user-images.githubusercontent.com/1162446/105396734-854c2180-5c20-11eb-9449-16c35859c747.png)

**Comment by Levrault** [comment] 2021-01-22 15:17
Hi @Delpher57 ,

I test on a Windows 10 machine but was not able to reproduce your problem. But I made some improvements that could fix the problem. https://github.com/Levrault/LE-dialogue-editor/pull/34

You can test version 1.1.0-beta https://github.com/Levrault/LE-dialogue-editor/releases/tag/v1.1.0-beta

But first of all, create a new workspace with the one, old .cfg could be depreciated now.
If this does not solve your issues, I will ask you to join me the log file `C:\Users\you_username\AppData\Roaming\Godot\app_userdata\LE-dialogue-editor`

**Comment by Levrault** [comment] 2021-07-05 18:26
Without any futhers feedbacks, I will close the issue

**Closed by Levrault** 2021-07-05 18:26 UTC
Labels: bug
